<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE queries [
	<!ELEMENT queries (query*)>
	<!ELEMENT query (use-case+, description,paginacao?,command+, ordenacoes?)>
	<!ELEMENT use-case    (#PCDATA)>
	<!ELEMENT description (#PCDATA)>
	<!ELEMENT command     (#PCDATA)>
	<!ELEMENT parametros  (#PCDATA)>
	<!ELEMENT paginar  (#PCDATA)>
	<!ELEMENT paginacao (#PCDATA)>
	<!ELEMENT colunaCodigo    (#PCDATA)>
	<!ELEMENT colunaDescricao    (#PCDATA)>
	<!ELEMENT numeroOcorrenciasPorPagina    (#PCDATA)>
	<!ELEMENT primeiraCondicao    (#PCDATA)>
	<!ELEMENT ascendente    (#PCDATA)>
	<!ELEMENT ordenacoes (ordenacao+)>
	<!ELEMENT ordenacao (#PCDATA)>
	<!ELEMENT sql  (#PCDATA)>
	<!ATTLIST ordenacao chave CDATA    #REQUIRED>
	<!ATTLIST ordenacao default CDATA    #IMPLIED>
	<!ATTLIST command parametros CDATA    #IMPLIED>
	<!ATTLIST command paginar CDATA    #IMPLIED>
	<!ATTLIST use-case name CDATA    #REQUIRED>
	<!ATTLIST query name CDATA    #REQUIRED>
	<!ATTLIST paginacao colunaCodigo CDATA    #REQUIRED>
	<!ATTLIST paginacao colunaDescricao CDATA    #REQUIRED>
	<!ATTLIST paginacao numeroOcorrenciasPorPagina CDATA    #REQUIRED>
	<!ATTLIST paginacao primeiraCondicao CDATA    #REQUIRED>
	<!ATTLIST paginacao ascendente CDATA    #REQUIRED>
	<!ATTLIST paginacao hint CDATA    #REQUIRED>
	<!ATTLIST paginacao hintAuxiliar CDATA   #IMPLIED>
]>
<queries>
	<query name="PROCESSAR_ATUALIZACAO_BOLETO_ADDA102RR2">
		<use-case name="Motor de Recebimento de Arquivos ADDA102RR2"></use-case>
	    <description>Processamento da atualização do XML da ADDA102RR2.</description>
	    <command>
			<![CDATA[
            /*Comando With para atualizar as tabelas restantes
              BOLETODDABAIXAEFET, BOLETODDABAIXAOPER, BOLETODDAGRUPOCALCULO, MENSAGEMDDA, MENSAGEMDDACONSULTABOLETO e LOGDETRECEBIMENTOOARQUIVODDA
              do processamento ADDA102RR2*/
            WITH 
            /*Cursor WITH que acessa a tabela LOGDETRECEBIMENTOOARQUIVODDA dos registros que serão processados*/
            LOGDETREC AS ( SELECT BOL.IDBOLETODDA,
                                  BOL.DATAVENCIMENTO,
                                  BOL.DATALIMITEPAGAMENTO,
                                  BOL.VALORBOLETO,
                                  BOL.NUMCODIGOBARRA,
                                  CASE
                                  /*Caso o Num. Sequência existente no arquivo XML for menor que o da BOLETODDA marca como concorrente para gravar erro 106
                                    Lembrando que abaixo foi colocado o valor HTML para o simbolo de menor para evitar erro na conversão do XML*/
                                  WHEN Y.NUMSEQATUALCADBOLETO &lt; BOL.NUMSEQATUALCADBOLETO THEN
                                   'CONCORRENTE106'
                                  /*Caso o Num. Sequência existente no arquivo XML for igual ao da BOLETODDA marca como concorrente e não faz nada com esse registro*/
                                  WHEN Y.NUMSEQATUALCADBOLETO = BOL.NUMSEQATUALCADBOLETO THEN
                                   'CONCORRENTE'
                                  /*Caso o Num. Sequência existente no arquivo XML for maior ao da BOLETODDA o campo MSG_CONCORRENTE ficará Nulo*/
                                  END MSG_CONCORRENTE,
                                  Y.INDRMANUTINSTCPGTOTIT,
                                  Y.GRPINSTRUCAOPAGAMENTOTITULO,
                                  Y.GRPCALCULO,
                                  --Y.INDRMANUTHISTNOTAFIS,
                                  --Y.GRPNOTAFISCAL,
                                  --Y.INDRMANUTHISTTXTINF,
                                  --Y.GRPTEXTOINFOBENEFICIARIO,
                                  Y.IDLOGDETRECEBIMENTOOARQUIVODDA,
                                  /*Essa lógica é realizada nesse ponto para que não seja carregado o XML desnecessáriamente na memoria*/
                                  CASE WHEN ( BOL.IDBOLETODDA IS NULL OR Y.NUMSEQATUALCADBOLETO &lt; BOL.NUMSEQATUALCADBOLETO ) THEN
                                     XMLSERIALIZE(Y.DESCXMLMENSAGEMRECEBIDA AS VARCHAR(30000))
                                  ELSE
                                     NULL
                                  END AS DESCXMLMENSAGEMRECEBIDA
                           FROM (
                           SELECT NUMIDENTIFICADORBOLETOCIP,
                                  NUMREFATUALCADBOLETO,
                                  NUMSEQATUALCADBOLETO,
                                  INDRMANUTINSTCPGTOTIT,
                                  GRPINSTRUCAOPAGAMENTOTITULO,
                                  GRPCALCULO,
                                  --INDRMANUTHISTNOTAFIS,
                                  --GRPNOTAFISCAL,
                                  --INDRMANUTHISTTXTINF,
                                  --GRPTEXTOINFOBENEFICIARIO,
                                  L.IDLOGDETRECEBIMENTOOARQUIVODDA,
                                  L.DESCXMLMENSAGEMRECEBIDA
                           FROM DDA.LOGDETRECEBIMENTOOARQUIVODDA L,
                                XMLTABLE ('$a/ArqRecebimento/Grupo_ADDA102RR2_Tit' passing DESCXMLMENSAGEMRECEBIDA as "a" 
                                          COLUMNS 
                                              NUMIDENTIFICADORBOLETOCIP                                   BIGINT                 PATH   'NumIdentcTit',
                                              NUMREFATUALCADBOLETO                                        BIGINT                 PATH   'NumRefAtlCadTit',
                                              NUMSEQATUALCADBOLETO                                        BIGINT                 PATH   'NumSeqAtlzCadTit',
                                              /*Indicadores (A-Atualizar, M-Manter) e seus respectivos grupos retornados como tipo XML conforme manual da CIP*/
                                              INDRMANUTINSTCPGTOTIT                                       CHAR(1)                PATH   'IndrManutInstcPgtoTit',
                                              GRPINSTRUCAOPAGAMENTOTITULO                                 XML                    PATH   'Grupo_ADDA102RR2_InstcPgtoTit',
                                              GRPCALCULO                                                  XML                    PATH   'Grupo_ADDA102RR2_Calc'
                                              --INDRMANUTHISTNOTAFIS                                        CHAR(1)                PATH   'IndrManutHistNotaFis',
                                              --GRPNOTAFISCAL                                               XML                    PATH   'Grupo_ADDA102RR2_NotaFis',
                                              --INDRMANUTHISTTXTINF                                         CHAR(1)                PATH   'IndrManutHistTxtInf',
                                              --GRPTEXTOINFOBENEFICIARIO                                    XML                    PATH   'TxtInfBenfcrio',
                                              /*  Fim dos Indicadores e grupos */
                                         ) AS X
                            WHERE L.IDLOGRECEBIMENTOOARQUIVODDA = <bancoob:valor valor="${idLogArquivoRecebido}"/>
                            AND   L.BOLPROCESSADO = 0
                            AND   L.IDLOGDETRECEBIMENTOOARQUIVODDA BETWEEN <bancoob:valor valor="${idLogDetArqInicial}"/> AND <bancoob:valor valor="${idLogDetArqFinal}"/>
                           ) Y
                           /*LEFT OUTER JOIN necessário para que todos os registros sejam retornados, viabilizando a gravação da tabela MENSAGEMDDA caso não seja encontrada a tupla na BOLETODDA*/
                           LEFT OUTER JOIN DDA.BOLETODDA BOL ON BOL.NUMIDENTIFICADORBOLETOCIP = Y.NUMIDENTIFICADORBOLETOCIP ),
            /*Cursor WITH que recupera um universo menor do cursor montado no primeiro WITH entitulado LOGDETREC
              LOGREC_INSTPAG: Esse cursor recupera somente os registros que terão que realizar a exclusão das tabelas de baixas operacional e efetiva*/
            LOGREC_INSTPAG AS (SELECT REC.IDBOLETODDA
                               FROM LOGDETREC REC,
                                    XMLTABLE ('$a/.' PASSING REC.GRPINSTRUCAOPAGAMENTOTITULO as "a"
                                    COLUMNS 
                                       DATAVENCIMENTO         DATE           PATH  'DtVencTit',
                                       VALORBOLETO            DECIMAL(18,2)  PATH  'VlrTit',
                                       DATALIMITEPAGAMENTO    DATE           PATH  'DtLimPgtoTit'
                                    ) AS B
                               WHERE REC.IDBOLETODDA IS NOT NULL
                               AND   REC.MSG_CONCORRENTE IS NULL
                               /*Somente retornar se no XML o indicador de Manutenção Instrução Pagamento Título for igual a A*/
                               AND   REC.INDRMANUTINSTCPGTOTIT = 'A'
                               /*Somente incluirá no cursor os registros que os campos DATAVENCIMENTO ou VALORBOLETO ou DATALIMITEPAGAMENTO 
                                 forem diferentes do XML forem diferentes do que está no boleto*/
                               AND   (CASE
                                        WHEN ( REC.DATAVENCIMENTO IS NULL     AND B.DATAVENCIMENTO IS NOT NULL ) OR
                                             ( REC.DATAVENCIMENTO IS NOT NULL AND B.DATAVENCIMENTO IS NULL ) OR
                                             ( REC.DATAVENCIMENTO != B.DATAVENCIMENTO ) THEN
                                           'EXCLUIR'
                                        WHEN ( REC.VALORBOLETO IS NULL     AND B.VALORBOLETO IS NOT NULL ) OR 
                                             ( REC.VALORBOLETO IS NOT NULL AND B.VALORBOLETO IS NULL ) OR
                                             ( REC.VALORBOLETO != B.VALORBOLETO ) THEN
                                           'EXCLUIR'
                                        WHEN ( REC.DATALIMITEPAGAMENTO IS NULL     AND B.DATALIMITEPAGAMENTO IS NOT NULL ) OR 
                                             ( REC.DATALIMITEPAGAMENTO IS NOT NULL AND B.DATALIMITEPAGAMENTO IS NULL ) OR
                                             ( REC.DATALIMITEPAGAMENTO != B.DATALIMITEPAGAMENTO ) THEN
                                           'EXCLUIR'
                                        ELSE 'NAO EXCLUIR'
                                      END ) = 'EXCLUIR'),
            /*Comando de DELETE utlizando o recurso FROM OLD TABLE do DB2 que recupera um cursor das tuplas que foram excluídas da tabela
              Os DELETEs abaixo retornarão somente a quantidade de registros que foram excluídos nos campos QTD_DELBAIXAEFT e QTD_DELBAIXAOPE
              As exclusões DELBAIXAEFT e DELBAIXAOPE serão realizadas somente para as tuplas encontradas na seleção LOGREC_INSTPAG
              Ou seja serão excluídas as baixas operacionais e efetivas dos registros que tiverem alterações nos campos 
              DATAVENCIMENTO ou VALORBOLETO ou DATALIMITEPAGAMENTO*/
            DELBAIXAEFT AS (SELECT COUNT(*) QTD_DELBAIXAEFT
                            FROM OLD TABLE ( DELETE FROM DDA.BOLETODDABAIXAEFET BAIXE
                                             WHERE BAIXE.IDBOLETODDA IN (SELECT REC.IDBOLETODDA FROM LOGREC_INSTPAG REC))),
            DELBAIXAOPE AS (SELECT COUNT(*) QTD_DELBAIXAOPE
                            FROM OLD TABLE ( DELETE FROM DDA.BOLETODDABAIXAOPER BAIXO
                                             WHERE BAIXO.IDBOLETODDA IN (SELECT REC.IDBOLETODDA FROM LOGREC_INSTPAG REC))),
            /*Os DELETES abaixo (DELNOTA e DELTXT) serão realizados se for identificado indicativo 
              de alteração para o grupo pesquisado em cada DELETE para que sejam posteriormente inseridos nos INSERTs
              que vem logo a seguir (INSBOLCALC, INSBOLNOTA e INSBOLTXT)
             */
            DELCALC AS (SELECT COUNT(*) QTD_DELCALC
                        FROM OLD TABLE ( DELETE FROM DDA.BOLETODDAGRUPOCALCULO CALC
                                         WHERE CALC.IDBOLETODDA IN (SELECT REC2.IDBOLETODDA
                                                                    FROM LOGDETREC REC2
                                                                    WHERE REC2.IDBOLETODDA IS NOT NULL
                                                                    AND   REC2.MSG_CONCORRENTE IS NULL
                                                                    AND   REC2.GRPCALCULO IS NOT NULL))),
            /* COMENTADO A PEDIDO DO RAFAEL
            DELNOTA AS (SELECT COUNT(*) QTD_DELNOTA
                          FROM OLD TABLE ( DELETE FROM DDA.BOLETODDANOTAFISCAL NOTA
                                           WHERE NOTA.IDBOLETODDA IN (SELECT REC2.IDBOLETODDA
                                                                      FROM LOGDETREC REC2
                                                                      WHERE REC2.IDBOLETODDA IS NOT NULL
                                                                      AND   REC2.MSG_CONCORRENTE IS NULL
                                                                      AND   REC2.INDRMANUTHISTNOTAFIS = 'A'
                                                                      AND   REC2.GRPNOTAFISCAL IS NOT NULL))),
            */
            /* COMENTADO A PEDIDO DO RAFAEL
            DELTXT AS (SELECT COUNT(*) QTD_DELTXT
                          FROM OLD TABLE ( DELETE FROM DDA.BOLETODDATEXTOINFO TXT
                                           WHERE TXT.IDBOLETODDA IN (SELECT REC2.IDBOLETODDA
                                                                     FROM LOGDETREC REC2
                                                                     WHERE REC2.IDBOLETODDA IS NOT NULL
                                                                     AND   REC2.MSG_CONCORRENTE IS NULL
                                                                     AND   REC2.INDRMANUTHISTTXTINF = 'A'
                                                                     AND   REC2.GRPTEXTOINFOBENEFICIARIO IS NOT NULL))),
            */
            INSBOLCALC AS (SELECT COUNT(*) QTD_BOLETOCALC
                           FROM FINAL TABLE (INSERT
                                             INTO DDA.BOLETODDAGRUPOCALCULO
                                             (IDBOLETODDA,
                                              VALORCALCULADOJUROS,
                                              VALORCALCULADOMULTA,
                                              VALORCALCULADODESCONTO,
                                              VALORTOTALCOBRADO,
                                              DATAVALIDADECALCULO)
                                             SELECT REC1.IDBOLETODDA,
                                                    B.VALORCALCULADOJUROS,
                                                    B.VALORCALCULADOMULTA,
                                                    B.VALORCALCULADODESCONTO,
                                                    B.VALORTOTALCOBRADO,
                                                    B.DATAVALIDADECALCULO
                                             FROM LOGDETREC REC1,
                                                  XMLTABLE ('$a/.' PASSING REC1.GRPCALCULO as "a"
                                                    COLUMNS 
                                                      VALORCALCULADOJUROS        DECIMAL(18,2)     PATH  'VlrCalcdJuros',
                                                      VALORCALCULADOMULTA        DECIMAL(18,2)     PATH  'VlrCalcdMulta',
                                                      VALORCALCULADODESCONTO     DECIMAL(18,2)     PATH  'VlrCalcdDesct',
                                                      VALORTOTALCOBRADO          DECIMAL(18,2)     PATH  'VlrTotCobrar',
                                                      DATAVALIDADECALCULO        DATE              PATH  'DtValiddCalc') AS B
                                             WHERE REC1.IDBOLETODDA IS NOT NULL
                                             AND   REC1.MSG_CONCORRENTE IS NULL
                                             AND   REC1.GRPCALCULO IS NOT NULL)),
            /* COMENTADO A PEDIDO DO RAFAEL
            INSBOLNOTA AS (SELECT COUNT(*) QTD_BOLETONOTA
                           FROM FINAL TABLE (INSERT
                                             INTO DDA.BOLETODDANOTAFISCAL
                                             (IDBOLETODDA,
                                              NUMNOTAFISCAL,
                                              DATAEMISSAONOTAFISCAL,
                                              VALORNOTAFISCAL)
                                             SELECT REC1.IDBOLETODDA,
                                                    B.NUMNOTAFISCAL,
                                                    B.DATAEMISSAONOTAFISCAL,
                                                    B.VALORNOTAFISCAL
                                             FROM LOGDETREC REC1,
                                                  XMLTABLE ('$a/.' PASSING REC1.GRPNOTAFISCAL as "a"
                                                    COLUMNS 
                                                       NUMNOTAFISCAL           VARCHAR(15)     PATH  'NumNotaFis',
                                                       DATAEMISSAONOTAFISCAL   DATE            PATH  'DtEmsNotaFis',
                                                       VALORNOTAFISCAL         DECIMAL(18,2)   PATH  'VlrNotaFis') AS B
                                             WHERE REC1.IDBOLETODDA IS NOT NULL
                                             AND   REC1.MSG_CONCORRENTE IS NULL
                                             AND   REC1.INDRMANUTHISTNOTAFIS = 'A'
                                             AND   REC1.GRPNOTAFISCAL IS NOT NULL)),
            */
            /* COMENTADO A PEDIDO DO RAFAEL
            INSBOLTXT AS (SELECT COUNT(*) QTD_BOLETOTXT
                           FROM FINAL TABLE (INSERT
                                             INTO DDA.BOLETODDATEXTOINFO
                                             (IDBOLETODDA,
                                              DESCTEXTOINFORMATIVO)
                                             SELECT REC1.IDBOLETODDA,
                                                    B.DESCTEXTOINFORMATIVO
                                             FROM LOGDETREC REC1,
                                                  XMLTABLE ('$a/.' PASSING REC1.GRPTEXTOINFOBENEFICIARIO as "a"
                                                    COLUMNS 
                                                       DESCTEXTOINFORMATIVO    VARCHAR(200)  PATH  '.') AS B
                                             WHERE REC1.IDBOLETODDA IS NOT NULL
                                             AND   REC1.MSG_CONCORRENTE IS NULL
                                             AND   REC1.INDRMANUTHISTTXTINF = 'A'
                                             AND   REC1.GRPTEXTOINFOBENEFICIARIO IS NOT NULL)),
            */
            /*O INSERT abaixo é responsável pela insersão da contingência na tabela MENSAGEMDDA para os registros que
              não foram encontrados na BOLETODDA (ERRO001) ou no BOLETODDA estão com o sequencial maior que o que 
              chegou no arquivo ADDA102RR2 (DDA0106)
              Nesse comando FROM FINAL TABLE optamos por retornar todos os dados inseridos para que os mesmos pudessem ser utilizados
              na gravação da tabela MENSAGEMDDACONSULTABOLETO
              Foi retornado também um count utilizando partition by default para que o DB2 retorne o numero de linhas total em todas as tuplas retornadas*/
            MSGDDA AS (SELECT
                       /*COUNT(*) OVER () QTD_MSGDDA,*/
                       IDMENSAGEMDDA, CODTIPOMENSAGEMDDA, XMLMENSAGEM
                       FROM FINAL TABLE ( INSERT 
                                          INTO DDA.MENSAGEMDDA (
                                            IDMENSAGEMDDAORIGEM,
                                            CODTIPOMENSAGEMDDA,
                                            DATAMOVIMENTO,
                                            DATAHORAMENSAGEM,
                                            QTDTOTREG,
                                            DATAHORAPROTOCOLO,
                                            NUMOPERACAO,
                                            DESCERROPROTOCOLO,
                                            XMLMENSAGEM,
                                            BOLORIGEMSICOOB,
                                            DATAHORACADASTRO,
                                            NUMPRIORIDADEENVIO,
                                            NUMCONTROLEDDA,
                                            IDUSUARIOSOLICITANTE,
                                            IDINSTITUICAOSOLICITANTE,
                                            IDCANAL )
                                          SELECT NULL AS IDMENSAGEMDDAORIGEM,
                                                 CASE
                                                    WHEN REC.MSG_CONCORRENTE = 'CONCORRENTE106' THEN
                                                       'DDA0106'
                                                    ELSE
                                                       'ERRO001'
                                                 END AS CODTIPOMENSAGEMDDA,
                                                 CURRENT DATE AS DATAMOVIMENTO,
                                                 NULL AS DATAHORAMENSAGEM,
                                                 NULL AS QTDTOTREG,
                                                 NULL AS DATAHORAPROTOCOLO,
                                                 NULL AS NUMOPERACAO,
                                                 NULL AS DESCERROPROTOCOLO,
                                                 REC.DESCXMLMENSAGEMRECEBIDA AS XMLMENSAGEM,
                                                 1 AS BOLORIGEMSICOOB,
                                                 CURRENT TIMESTAMP AS DATAHORACADASTRO,
                                                 10 AS NUMPRIORIDADEENVIO,
                                                 NULL AS NUMCONTROLEDDA,
                                                 'DDA-CIP' AS IDUSUARIOSOLICITANTE,
                                                 '1' AS IDINSTITUICAOSOLICITANTE,
                                                 1 AS IDCANAL
                                          FROM LOGDETREC REC
                                          WHERE ( REC.IDBOLETODDA IS NULL OR REC.MSG_CONCORRENTE = 'CONCORRENTE106' ) ) ),
            /*Abaixo será realizado o insert da tabela MENSAGEMDDACONSULTABOLETO que é filha da tabela MENSAGEMDDA e somente é gravada 
              para os casos de mensagem DDA0106, que ocorre quando o sequencial da BOLETODDA é maior que a do arquivo.
              Então o insert é realizado baseado no retorno do FROM FINAL TABLE realizado no comando WITH MSGDDA*/
            MSGCONSULTADDA AS (SELECT COUNT(*) QTD_MSGCONSDDA
                               FROM FINAL TABLE ( INSERT INTO DDA.MENSAGEMDDACONSULTABOLETO
                                                  (IDMENSAGEMDDA,NUMCODIGOBARRA,NUMCPFCNPJPAGADOR,CODSITUACAOBOLETO,NUMIDENTIFICADORBOLETOCIPINICIAL,NUMIDENTIFICADORBOLETOCIPFINAL,CODTIPOBOLETOCONSULTADO)
                                                  SELECT MS.IDMENSAGEMDDA,
                                                         NULL,
                                                         NULL,
                                                         NULL,
                                                         X.NUMIDENTIFICADORBOLETOCIP,
                                                         X.NUMIDENTIFICADORBOLETOCIP,
                                                         'T' AS CODTIPOBOLETOCONSULTADO
                                                  FROM MSGDDA MS,
                                                       XMLTABLE ('$a/ArqRecebimento/Grupo_ADDA102RR2_Tit' passing XMLPARSE( DOCUMENT XMLMENSAGEM ) as "a" 
                                                       COLUMNS 
                                                       NUMIDENTIFICADORBOLETOCIP    BIGINT   PATH    'NumIdentcTit' ) AS X
                                                  WHERE MS.CODTIPOMENSAGEMDDA = 'DDA0106' ) )
            /*
            Consulta de apoio para repurar os quantitativos alterados em caso de teste da query (Em caso de uso substituir SELECT 1 AS DUMMY FROM SYSIBM.SYSDUMMY1 por esse)
            SELECT A1.QTD_DELBAIXAEFT, A2.QTD_DELBAIXAOPE, A4.QTD_DELCALC, A6.QTD_BOLETOCALC,A7.QTD_MSGDDA, A8.QTD_MSGCONSDDA
                   ,A10.QTD_DELNOTA, A11.QTD_DELTXT,A12.QTD_BOLETONOTA, A13.QTD_BOLETOTXT
            FROM DELBAIXAEFT A1, DELBAIXAOPE A2, DELDESCON A3, DELCALC A4, INSBOLDESC A5, INSBOLCALC A6,
                 (SELECT COALESCE(AA.QTD_MSGDDA,0) QTD_MSGDDA FROM SYSIBM.SYSDUMMY1 LEFT OUTER JOIN MSGDDA AA ON AA.QTD_MSGDDA IS NOT NULL FETCH FIRST 1 ROW ONLY) A7,
                 MSGCONSULTADDA A8
                 ,DELNOTA A10, DELTXT A11, INSBOLNOTA A12, INSBOLTXT A13
            */
            /*Esse aqui é o SELECT que realmente retornará no final da execução de todo o comando*/
            SELECT 1 AS DUMMY FROM SYSIBM.SYSDUMMY1
			
			]]>
		</command>
	</query>
	
	<query name="GRAVAR_CAMPOS_BOLETO_ADDA102RR2">
		<use-case name="Motor de Recebimento de Arquivos ADDA102RR2"></use-case>
	    <description>Processamento da atualização dos campos da BoletoDDA a partir do XML da ADDA102RR2.</description>
	    <command>
			<![CDATA[
            /*Comando MERGE para realizar UPDATE baseadas nos resultados dos grupos
              Beneficiário Original, Beneficiario Final, Pagador, Avalista, Documento Título, Instrução Pagamento e Instrução Valor Recebimento
              e que  sequencial do XML seja maior que o do boleto
              ATENCAO, esse UPDATE tem que ser o ultimo a ser executado pois o NUMSEQATUALCADBOLETO será alterado nessa query e as demais queries verificam esse campo.*/
            MERGE INTO DDA.BOLETODDA BUP
            USING (
            SELECT XML1.NUMIDENTIFICADORBOLETOCIP,
                   XML1.NUMREFATUALCADBOLETO,
                   XML1.NUMSEQATUALCADBOLETO,
                   XML1.CODISPBPARTDESTINATARIO,
                   /*Campos dos Grupos*/
                   XML1.INDRMANUTBENFCRIOOR,
                   --XML1.GRPBENEFICIARIOORIGINAL,
                   XML1.INDRMANUTBENFCRIOFINL,
                   --XML1.GRPBENEFICIARIOFINAL,
                   XML1.INDRMANUTPAGDRTIT,
                   --XML1.GRPPAGADOR,
                   XML1.INDRMANUTSACDRAVALST,
                   --XML1.GRPSACADORAVALISTA,
                   XML1.INDRMANUTDOCTIT,
                   --XML1.GRPDOCUMENTOTITULO,
                   XML1.INDRMANUTINSTCPGTOTIT,
                   --XML1.GRPINSTRUCAOPAGAMENTOTITULO,
                   XML1.INDRMANUTINSTCVLRRECBT,
                   --XML1.GRPINSTRUCAOVALORRECEBIMENTO,
                   /* Fim dos campos de grupo*/
                   XML1.QTDPAGAMENTOPARCIALREG,
                   XML1.VALORSALDOPAGAMENTO,
                   XML1.CODSITUACAOBOLETOPAGAMENTO,
                   XML1.DATAHORASITUACAOBOLETO,
                   L.IDLOGDETRECEBIMENTOOARQUIVODDA,
                   --L.DESCXMLMENSAGEMRECEBIDA,
                   /*Campos Beneficiário Original*/
                   BENO.NOMEFANTASIABENEFICIARIO,
                   BENO.DESCLOGRADOUROBENEFICIARIO,
                   BENO.DESCCIDADEBENEFICIARIO,
                   BENO.SIGLAUFBENEFICIARIO,
                   BENO.NUMCEPBENEFICIARIO,
                   /*Campos Beneficiario Final*/
                   BENF.CODTIPOPESSOABENEFICIARIOFINAL,
                   BENF.NUMCPFCNPJBENEFICIARIOFINAL,
                   BENF.NOMEBENEFICIARIOFINAL,
                   BENF.NOMEFANTASIABENEFICIARIOFINAL,
                   /*Campos Pagador*/
                   PAG.NOMEPAGADOR,
                   PAG.NOMEFANTASIAPAGADOR,
                   PAG.DESCLOGRADOUROPAGADOR,
                   PAG.DESCCIDADEPAGADOR,
                   PAG.SIGLAUFPAGADOR,
                   PAG.NUMCEPPAGADOR,
                   /*Campos Avalista*/
                   AVAL.CODTIPOPESSOADDAAVALISTA,
                   AVAL.NUMCPFCNPJAVALISTA,
                   AVAL.NOMEAVALISTA,
                   /*Campos Documento Título*/
                   DOCT.IDCARTEIRA,
                   DOCT.NUMDOCUMENTO,
                   DOCT.IDESPECIEDOCUMENTO,
                   DOCT.CODTIPOPAGAMENTO,
                   DOCT.NUMPARCELA,
                   DOCT.QTDTOTALPARCELA,
                   DOCT.BOLTITULONEGOCIADO,
                   /*Campos Instrução Pagamento*/
                   INSPG.DATAVENCIMENTO,
                   INSPG.VALORBOLETO,
                   INSPG.NUMDIASPROTESTO,
                   INSPG.DATALIMITEPAGAMENTO,
                   INSPG.BOLBLOQUEIOPAGAMENTO,
                   INSPG.VALORABATIMENTO,
                   INSPG.QTDPAGAMENTOPARCIAL,
                   INSPG.CODTIPOMODELOCALCULO,
                   /*Campos Instrução Valor Recebimento*/
                   INSVR.CODAUTORIZACAOVALORDIVERGENTE,
                   INSVR.CODINDICADORVALORMINIMO,
                   INSVR.VALORMINIMO,
                   INSVR.CODINDICADORVALORMAXIMO,
                   INSVR.VALORMAXIMO,
                   XML1.INDRMANUTJUROSTIT,
                   JUROS.DATAJUROS,
                   JUROS.CODTIPOJUROS,
                   JUROS.VALORPERCENTUALJUROS,
                   XML1.INDRMANUTMULTATIT,
                   MULTA.DATAMULTA,
                   MULTA.CODTIPOMULTA,
                   MULTA.VALORPERCENTUALMULTA,
                   XML1.INDRMANUTDESCTTIT,