<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE queries [
<!ELEMENT queries (query*)>
<!ELEMENT query (use-case+, description,paginacao?,command+, projecao?, ordenacoes?)>
<!ELEMENT use-case    (#PCDATA) >
<!ELEMENT description (#PCDATA) >
<!ELEMENT command     (#PCDATA) >
<!ELEMENT parametros  (#PCDATA) >
<!ELEMENT projecao (#PCDATA) >
<!ELEMENT paginar  (#PCDATA) >
<!ELEMENT paginacao (#PCDATA) >
<!ELEMENT colunaCodigo    (#PCDATA) >
<!ELEMENT colunaDescricao    (#PCDATA) >
<!ELEMENT numeroOcorrenciasPorPagina    (#PCDATA) >
<!ELEMENT primeiraCondicao    (#PCDATA) >
<!ELEMENT ascendente    (#PCDATA) >
<!ELEMENT ordenacoes (ordenacao+)>
<!ELEMENT ordenacao (#PCDATA)>
<!ELEMENT sql  (#PCDATA) >
<!ATTLIST ordenacao chave CDATA    #REQUIRED >
<!ATTLIST ordenacao default CDATA    #IMPLIED >
<!ATTLIST command parametros CDATA    #IMPLIED  >
<!ATTLIST command paginar CDATA    #IMPLIED  >
<!ATTLIST use-case name CDATA    #REQUIRED >
<!ATTLIST query name CDATA    #REQUIRED >
<!ATTLIST paginacao colunaCodigo CDATA    #REQUIRED>
<!ATTLIST paginacao colunaDescricao CDATA    #REQUIRED>
<!ATTLIST paginacao numeroOcorrenciasPorPagina CDATA    #REQUIRED>
<!ATTLIST paginacao primeiraCondicao CDATA    #REQUIRED>
<!ATTLIST paginacao ascendente CDATA    #REQUIRED>
<!ATTLIST paginacao hint CDATA    #REQUIRED>
<!ATTLIST paginacao hintAuxiliar CDATA   #IMPLIED >
]>
<queries>


	<query name="CRIA_TABELA_TEMPORARIA_ARQUIVAMENTO">
		<use-case name="CRIA_TABELA_TEMPORARIA_ARQUIVAMENTO"></use-case>
		<description>Criacao da tabela temporaria para gravar os IDs das mensagens que serao arquivadas</description>
		<command>
				<![CDATA[
				DECLARE GLOBAL TEMPORARY TABLE SESSION.TMP_MENSAGEMDDA_ARQUIVAMENTO ( IDMENSAGEMDDA    BIGINT,
				                                                                      NUMAGRUPAMENTO   BIGINT,
				                                                                      BOLORIGEM        SMALLINT)
				ON COMMIT PRESERVE ROWS
				NOT LOGGED ON ROLLBACK DELETE ROWS
				WITH REPLACE
				]]>
		</command>
	</query>

	<query name="CRIA_INDICE_TABELA_TEMPORARIA_ARQUIVAMENTO">
		<use-case name="CRIA_INDICE_TABELA_TEMPORARIA_ARQUIVAMENTO"></use-case>
		<description>CRIA_INDICE_TABELA_TEMPORARIA_ARQUIVAMENTO</description>
		<command>
				<![CDATA[
				CREATE INDEX SESSION.TEMP_IDX_MENSAGEMDDA_ARQUIVAMENTO ON SESSION.TMP_MENSAGEMDDA_ARQUIVAMENTO(NUMAGRUPAMENTO ASC, BOLORIGEM ASC) ALLOW REVERSE SCANS
				]]>
		</command>
	</query>

	<query name="RUNSTATS_TABELA_TEMPORARIA_ARQUIVAMENTO">
		<use-case name="RUNSTATS_TABELA_TEMPORARIA_ARQUIVAMENTO"></use-case>
		<description>RUNSTATS_TABELA_TEMPORARIA_ARQUIVAMENTO</description>
		<command>
				<![CDATA[
				CALL ADMIN_CMD ('RUNSTATS ON TABLE SESSION.TMP_MENSAGEMDDA_ARQUIVAMENTO WITH DISTRIBUTION AND DETAILED INDEXES ALL')
				]]>
		</command>
	</query>

	<query name="CURSOR_ARQUIVAMENTO_MENSAGENS">
		<use-case name="CURSOR_ARQUIVAMENTO_MENSAGENS"></use-case>
		<description>CURSOR_ARQUIVAMENTO_MENSAGENS</description>
		<command>
				<![CDATA[
				SELECT DISTINCT MSG.NUMAGRUPAMENTO, MSG.BOLORIGEM 
				FROM SESSION.TMP_MENSAGEMDDA_ARQUIVAMENTO MSG
				ORDER BY MSG.NUMAGRUPAMENTO, MSG.BOLORIGEM
				]]>
		</command>
	</query>
</queries>
