<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE queries [
	<!ELEMENT queries (query*)>
	<!ELEMENT query (use-case+, description,paginacao?,command+, ordenacoes?)>
	<!ELEMENT use-case    (#PCDATA)>
	<!ELEMENT description (#PCDATA)>
	<!ELEMENT command     (#PCDATA)>
	<!ELEMENT parametros  (#PCDATA)>
	<!ELEMENT paginar  (#PCDATA)>
	<!ELEMENT paginacao (#PCDATA)>
	<!ELEMENT colunaCodigo    (#PCDATA)>
	<!ELEMENT colunaDescricao    (#PCDATA)>
	<!ELEMENT numeroOcorrenciasPorPagina    (#PCDATA)>
	<!ELEMENT primeiraCondicao    (#PCDATA)>
	<!ELEMENT ascendente    (#PCDATA)>
	<!ELEMENT ordenacoes (ordenacao+)>
	<!ELEMENT ordenacao (#PCDATA)>
	<!ELEMENT sql  (#PCDATA)>
	<!ATTLIST ordenacao chave CDATA    #REQUIRED>
	<!ATTLIST ordenacao default CDATA    #IMPLIED>
	<!ATTLIST command parametros CDATA    #IMPLIED>
	<!ATTLIST command paginar CDATA    #IMPLIED>
	<!ATTLIST use-case name CDATA    #REQUIRED>
	<!ATTLIST query name CDATA    #REQUIRED>
	<!ATTLIST paginacao colunaCodigo CDATA    #REQUIRED>
	<!ATTLIST paginacao colunaDescricao CDATA    #REQUIRED>
	<!ATTLIST paginacao numeroOcorrenciasPorPagina CDATA    #REQUIRED>
	<!ATTLIST paginacao primeiraCondicao CDATA    #REQUIRED>
	<!ATTLIST paginacao ascendente CDATA    #REQUIRED>
	<!ATTLIST paginacao hint CDATA    #REQUIRED>
	<!ATTLIST paginacao hintAuxiliar CDATA   #IMPLIED>
]>

<queries>
	<query name="OBTER_MONITORACAO_DDA0110">
		<use-case name="OBTER_MONITORACAO_DDA0110"></use-case>
		<description>OBTER_MONITORACAO_DDA0110</description>
		<command>
			<![CDATA[
				WITH PARAMETRO AS ( SELECT PAR.IDPARAMETRO, 
					                           CAST(PAR.VALORBASEPARAMETRO AS SMALLINT) AS VALORBASEPARAMETRO, 
					                           TO_TIMESTAMP(<bancoob:valor valor="${dataHoraUltimaAfericao}"/>,'YYYY-MM-DD HH24:MI:SSFF') AS DATAHORAULTIMAAFERICAO
					                    FROM DDA.PARAMETRO PAR WHERE PAR.IDPARAMETRO = 65 )
					SELECT COALESCE( SUM( CASE WHEN MSG.BOLEXCEDEUSLA = 0 THEN 1 ELSE 0 END),0) AS QTD_MSG_TOTAL_OK,
					       COALESCE( SUM( CASE WHEN MSG.BOLEXCEDEUSLA = 1 THEN 1 ELSE 0 END),0) AS QTD_MSG_TOTAL_SLA,
					       COALESCE( SUM( CASE
					                          WHEN MSG.BOLEXCEDEUSLA = 0 AND
					                               MSG.DATAHORAMENSAGEM  &gt; COALESCE(DATAHORAULTIMAAFERICAO, CURRENT TIMESTAMP - VALORBASEPARAMETRO SECONDS) AND
					                               MSG.DATAHORAMENSAGEM  &lt;= CURRENT TIMESTAMP
					                          THEN 1
					                          ELSE 0
					                      END),0) AS QTD_MSG_PERIODO_AFERICAO_OK,
					       COALESCE( SUM( CASE
					                          WHEN MSG.BOLEXCEDEUSLA = 1 AND
					                               MSG.DATAHORAMENSAGEM  &gt; COALESCE(DATAHORAULTIMAAFERICAO, CURRENT TIMESTAMP - VALORBASEPARAMETRO SECONDS) AND 
					                               MSG.DATAHORAMENSAGEM  &lt;= CURRENT TIMESTAMP
					                          THEN 1
					                          ELSE 0
					                      END),0) AS QTD_MSG_PERIODO_AFERICAO_SLA,
					       VARCHAR_FORMAT(CURRENT TIMESTAMP, 'YYYY-MM-DD HH24:MI:SSFF') AS DATAHORAAFERICAO,
					       VARCHAR_FORMAT(CURRENT TIMESTAMP, 'HH24:MI:SS') AS HORAAFERICAO,
					       MIN(PAR.VALORBASEPARAMETRO) AS TEMPOATUALIZACAO
					FROM PARAMETRO PAR
					LEFT OUTER JOIN DDA.MENSAGEMDDA MSG ON MSG.CODTIPOMENSAGEMDDA = 'DDA0110' AND
					                                       MSG.DATAHORAMENSAGEM BETWEEN CURRENT DATE AND CURRENT TIMESTAMP
			]]>
		</command>
	</query>
	<query name="OBTER_MONITORACAO_DEMAIS_MENSAGENS">
		<use-case name="OBTER_MONITORACAO_DEMAIS_MENSAGENS"></use-case>
		<description>OBTER_MONITORACAO_DEMAIS_MENSAGENS</description>
		<command>
			<![CDATA[
				SELECT SUM(CASE WHEN M.CODSITUACAOMENSAGEMDDA = 1 THEN 1 ELSE 0 END) AS QTD_STATUS_A_ENVIAR,
				       SUM(CASE WHEN M.CODSITUACAOMENSAGEMDDA = 2 OR M.CODSITUACAOMENSAGEMDDA = 9 THEN 1 ELSE 0 END) AS QTD_STATUS_SEM_PROTOCOLO,
				       SUM(CASE WHEN M.CODSITUACAOMENSAGEMDDA = 3 THEN 1 ELSE 0 END) AS QTD_STATUS_SEM_RETORNO_CIP,
				       SUM(CASE WHEN M.CODSITUACAOMENSAGEMDDA = 4 THEN 1 ELSE 0 END) AS QTD_STATUS_RETORNO_COM_ERRO,
				       CASE WHEN SUM(CASE WHEN M.DATAHORAMENSAGEM IS NULL AND M.DATAMOVIMENTO &lt;= CURRENT TIMESTAMP AND C.IDGRADEHORARIA IS NULL THEN 1 ELSE 0 END) &gt; 0 THEN 1 ELSE 0 END AS BOLFORADAGRADE,
				       CASE WHEN SUM(CASE WHEN M.CODSITUACAOMENSAGEMDDA = 9 THEN 1 ELSE 0 END) &gt; 0 THEN 1 ELSE 0 END AS BOL_SEM_PROTOCOLO
				FROM DDA.MENSAGEMDDA M
				JOIN DDA.TIPOMENSAGEMDDA TM ON TM.CODTIPOMENSAGEMDDA = M.CODTIPOMENSAGEMDDA
				LEFT OUTER JOIN DDA.GRADEHORARIA C ON C.DATAREFERENCIA = M.DATAMOVIMENTO AND C.CODTIPOGRADEHORARIA = TM.CODTIPOGRADEHORARIA
				WHERE TM.CODCATEGORIAMENSAGEMDDA = 'E'
				AND M.CODTIPOMENSAGEMDDA != 'DDA0110'
				AND M.BOLMENSAGEMPENDENTE = 1

			]]>
		</command>
	</query>
	<query name="OBTER_MONITORACAO_ARQUIVO_REMESSA">
		<use-case name="OBTER_MONITORACAO_ARQUIVO_REMESSA"></use-case>
		<description>OBTER_MONITORACAO_ARQUIVO_REMESSA</description>
		<command>
			<![CDATA[
				SELECT SUM(CASE WHEN M.CODSITUACAOMENSAGEMDDA = 1 THEN 1 ELSE 0 END) AS QTD_STATUS_A_ENVIAR,
				       SUM(CASE WHEN M.CODSITUACAOMENSAGEMDDA = 2 OR M.CODSITUACAOMENSAGEMDDA = 9 THEN 1 ELSE 0 END) AS QTD_STATUS_SEM_PROTOCOLO,
				       SUM(CASE WHEN M.CODSITUACAOMENSAGEMDDA = 3 THEN 1 ELSE 0 END) AS QTD_STATUS_SEM_RETORNO_CIP,
				       SUM(CASE WHEN M.CODSITUACAOMENSAGEMDDA = 4 THEN 1 ELSE 0 END) AS QTD_STATUS_RETORNO_COM_ERRO,
				       CASE WHEN SUM(CASE WHEN M.DATAHORAMENSAGEM IS NULL AND M.DATAMOVIMENTO &lt;= CURRENT TIMESTAMP AND C.IDGRADEHORARIA IS NULL THEN 1 ELSE 0 END) &gt; 0 THEN 1 ELSE 0 END AS BOLFORADAGRADE,
				       CASE WHEN SUM(CASE WHEN M.CODSITUACAOMENSAGEMDDA = 9 THEN 1 ELSE 0 END) &gt; 0 THEN 1 ELSE 0 END AS BOL_SEM_PROTOCOLO
				FROM DDA.MENSAGEMDDA M
				JOIN DDA.TIPOMENSAGEMDDA TM ON TM.CODTIPOMENSAGEMDDA = M.CODTIPOMENSAGEMDDA
				LEFT OUTER JOIN DDA.GRADEHORARIA C ON C.DATAREFERENCIA = M.DATAMOVIMENTO AND C.CODTIPOGRADEHORARIA = TM.CODTIPOGRADEHORARIA
				WHERE TM.CODCATEGORIAMENSAGEMDDA = 'A'
				AND M.BOLMENSAGEMPENDENTE = 1
			]]>
		</command>
	</query>
	<query name="LISTAR_GEN0015">
		<use-case name="LISTAR_GEN0015"></use-case>
		<description>LISTAR_GEN0015</description>
		<command>
			<![CDATA[
				SELECT new br.com.sicoob.sisbr.sicoobdda.entidades.LogRecebimentoArquivoDDA (
						arq.id,
						arq.descNomeArquivoRecebido,
						arq.dataHoraArquivo,
						arq.dataMovimento,
						arq.tipoMensagemDDA.codTipoMensagem,
						arq.tipoArquivo.codTipoArquivo,
						arq.situacaoProcessamentoArquivo.codSituacaoProcessamentoArquivo
					)
					FROM LogRecebimentoArquivoDDA arq
				WHERE arq.dataMovimento &gt;= <bancoob:valorOql valor="${dataMovimento}"/>
				ORDER BY arq.dataHoraArquivo
			]]>
		</command>
	</query>
	<query name="OBTER_DETALHE_MONITORACAO">
		<use-case name="OBTER_DETALHE_MONITORACAO"></use-case>
		<description>OBTER_DETALHE_MONITORACAO</description>
		<command>
			<![CDATA[
			SELECT M.DATAMOVIMENTO,
			       M.CODTIPOMENSAGEMDDA,
			       SUM(CASE WHEN M.CODSITUACAOMENSAGEMDDA = 1 THEN 1 ELSE 0 END) AS QTD_STATUS_A_ENVIAR,
			       SUM(CASE WHEN M.CODSITUACAOMENSAGEMDDA = 2 OR M.CODSITUACAOMENSAGEMDDA = 9 THEN 1 ELSE 0 END) AS QTD_STATUS_SEM_PROTOCOLO,
			       SUM(CASE WHEN M.CODSITUACAOMENSAGEMDDA = 3 THEN 1 ELSE 0 END) AS QTD_STATUS_SEM_RETORNO_CIP,
			       SUM(CASE WHEN M.CODSITUACAOMENSAGEMDDA = 4 THEN 1 ELSE 0 END) AS QTD_STATUS_RETORNO_COM_ERRO
			FROM DDA.MENSAGEMDDA M
			JOIN DDA.TIPOMENSAGEMDDA TM ON TM.CODTIPOMENSAGEMDDA = M.CODTIPOMENSAGEMDDA 
			WHERE TM.CODCATEGORIAMENSAGEMDDA = <bancoob:valor valor="${codCategoriaMensagemDDA}"/>
			AND TM.CODTIPOMENSAGEMDDA != 'DDA0110'
			AND M.BOLMENSAGEMPENDENTE = 1
			GROUP BY M.DATAMOVIMENTO, M.CODTIPOMENSAGEMDDA
			]]>
		</command>
	</query>
	<query name="OBTER_DADOS_MONITORACAO_ERRO">
		<use-case name="OBTER_DADOS_MONITORACAO_ERRO"></use-case>
		<description>OBTER_DADOS_MONITORACAO_ERRO</description>
		<command>
			<![CDATA[
				SELECT TEC.CODTIPOERROCIP,
				       TEC.DESCTIPOERROCIP AS DESCTIPOERROCIP,
				       COUNT(*) AS QTD_ERROS
				from dda.MENSAGEMDDA MRET
				JOIN DDA.ERROMENSAGEMRETORNOCIP MERC ON MERC.IDMENSAGEMDDA = MRET.IDMENSAGEMDDA AND
				                                        MERC.CODTIPOTRATAMENTOERROCIP IS NULL
				JOIN DDA.TIPOERROCIP TEC ON TEC.CODTIPOERROCIP = MERC.CODTIPOERROCIP
				WHERE MRET.IDMENSAGEMDDAORIGEM IN ( SELECT m.IDMENSAGEMDDA
				                                    FROM DDA.MENSAGEMDDA M
				                                    JOIN DDA.TIPOMENSAGEMDDA TM ON TM.CODTIPOMENSAGEMDDA = M.CODTIPOMENSAGEMDDA
				                                    WHERE M.BOLMENSAGEMPENDENTE = 1
				                                    AND M.CODSITUACAOMENSAGEMDDA = 4
				                                    AND TM.CODCATEGORIAMENSAGEMDDA = <bancoob:valor valor="${codCategoriaMensagemDDA}"/>
				                                    AND TM.CODTIPOMENSAGEMDDA != 'DDA0110'
				                                    AND TM.BOLEXIGEMENSAGEMRETORNO = 1 )
				GROUP BY TEC.CODTIPOERROCIP, 
				         TEC.DESCTIPOERROCIP
				UNION
				SELECT NULL AS CODTIPOERROCIP,
				       M.DESCERROPROTOCOLO AS DESCTIPOERROCIP,
				       COUNT(*) AS QTD_ERROS
				FROM DDA.MENSAGEMDDA M
				JOIN DDA.TIPOMENSAGEMDDA TM ON TM.CODTIPOMENSAGEMDDA = M.CODTIPOMENSAGEMDDA
				WHERE M.BOLMENSAGEMPENDENTE = 0
				AND M.CODSITUACAOMENSAGEMDDA = 9
				AND TM.CODCATEGORIAMENSAGEMDDA = <bancoob:valor valor="${codCategoriaMensagemDDA}"/>
				AND TM.CODTIPOMENSAGEMDDA != 'DDA0110'
				AND TM.BOLEXIGEMENSAGEMRETORNO = 1
				GROUP BY M.DESCERROPROTOCOLO
				ORDER BY 3 DESC
			]]>
		</command>
	</query>
	<query name="OBTER_MONITORACAO_DDA0110_CONTINGENCIA">
		<use-case name="OBTER_MONITORACAO_DDA0110_CONTINGENCIA"></use-case>
		<description>OBTER_MONITORACAO_DDA0110_CONTINGENCIA</description>
		<command>
			<![CDATA[
				WITH PARAMETRO AS ( SELECT PAR.IDPARAMETRO, CAST(PAR.VALORBASEPARAMETRO AS SMALLINT) AS VALORBASEPARAMETRO 
				                    FROM DDA.PARAMETRO PAR WHERE PAR.IDPARAMETRO = 111 )
					SELECT COALESCE( SUM( CASE
					                          WHEN MSG.BOLEXCEDEUSLA = 0 AND
					                               MSG.DATAHORAMENSAGEM  &gt; (CURRENT TIMESTAMP - VALORBASEPARAMETRO SECONDS) AND
					                               MSG.DATAHORAMENSAGEM  &lt;= CURRENT TIMESTAMP
					                          THEN 1
					                          ELSE 0
					                      END),0) AS QTD_MSG_PERIODO_AFERICAO_OK,
					       COALESCE( SUM( CASE
					                          WHEN MSG.BOLEXCEDEUSLA = 1 AND
					                               MSG.DATAHORAMENSAGEM  &gt; (CURRENT TIMESTAMP - VALORBASEPARAMETRO SECONDS) AND 
					                               MSG.DATAHORAMENSAGEM  &lt;= CURRENT TIMESTAMP
					                          THEN 1
					                          ELSE 0
					                      END),0) AS QTD_MSG_PERIODO_AFERICAO_SLA
					FROM PARAMETRO PAR
					LEFT OUTER JOIN DDA.MENSAGEMDDA MSG ON MSG.CODTIPOMENSAGEMDDA = 'DDA0110' AND MSG.DATAHORAMENSAGEM BETWEEN CURRENT DATE AND CURRENT TIMESTAMP
			]]>
		</command>
	</query>
</queries>
